products = [{
        id: 100,
        name: 'cat',
        price: 60,
        instock: 10,
        description: "beautiful small cat",
        images: "images/cat.jpg",
    },
    {
        id: 200,
        name: 'dog',
        price: 70,
        instock: 15,
        description: "lovely dog",
        images: "images/dog.jpg",
    },
    {
        id: 300,
        name: 'small duck',
        price: 100,
        instock: 7,
        description: "small beautiful",
        images: "images/small duck.jpg",
    },
    {
        id: 400,
        name: 'bird ',
        price: 150,
        instock: 20,
        description: "beautiful bird",
        images: "images/bird.png",
    },
    {
        id: 500,
        name: 'turtle',
        price: 110,
        instock: 5,
        description: "small turtle",
        images: "images/turtle.jpg",
    },
    {
        id: 600,
        name: 'hamster',
        price: 90,
        instock: 0,
        description: "lovely hamster",
        images: "images/hamster.jpg",
    },
    {
        id: 700,
        name: 'colored fish',
        price: 50,
        instock: 30,
        description: "lovely colored fish",
        images: "images/fish.jpg",
    },
    {
        id: 800,
        name: 'small monkey',
        price: 30,
        instock: 25,
        description: "small beautiful monkey",
        images: "images/monkey.jpg",
    },
    {
        id: 900,
        name: '	hedgehogs',
        price: 80,
        instock: 10,
        description: "	hedgehogs",
        images: "images/gn.webp",
    }
]